AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Star Wars CRUD

Globals:
    Function:
        Timeout: 3
        Runtime: nodejs18.x
        CodeUri: src/
        Environment:
            Variables:
                DATABASE_NAME: star-wars

Resources:
    Table:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: star-wars
            PrimaryKey:
                Name: id
                Type: String

    CreateFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: create-person
            Handler: index.createHandler
            Architectures:
                - x86_64
            Events:
                Entity:
                    Type: Api
                    Properties:
                        Path: /
                        Method: POST
            Policies:
                - DynamoDBWritePolicy:
                      TableName: !Ref Table

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                EntryPoints:
                    - index.ts
    FindFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: find-person
            Handler: index.findHandler
            Architectures:
                - x86_64
            Events:
                Entity:
                    Type: Api
                    Properties:
                        Path: /{id}
                        Method: GET
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref Table

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                EntryPoints:
                    - index.ts
